# Imports

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('/workspace/deep_birth_death/src/')

In [3]:
import pickle
import itertools
import time
import os
import statistics
from time import time

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from evaluation.regression import get_regression_metrics, plot_errors, plot_errors_boxplot, predicted_minus_target_vs_target, get_clipping_results

In [4]:
pd.options.display.float_format = "{:,.4f}".format

# Results generation

In [10]:
pickle_base = '/workspace/deep_birth_death/deep_learning/pickles/treepar_dataset/dataset_'
res_path = "/workspace/deep_birth_death/deep_learning/models/reg/"
n_tips = ['674', '489', '87']

data = dict()
for i in n_tips:
    with open(pickle_base + i + ".pkl", 'rb') as f:
        data[i] = pickle.load(f)

In [8]:
n_trees_tested = 1000
results = dict()
inf_times = dict()

for i in n_tips:
    print('---', i, 'tips ---')
    results[i] = dict()
    inf_times[i] = dict()
    
    for label in np.unique(data[i]['div_info_test']):
        div_scenario = label.split('/')[1].split('_')[0]
        results[i][div_scenario] = dict()
        inf_times[i][div_scenario] = dict()
        
        norm_types = ['norm', 'no_norm']
        for norm in norm_types:
            results[i][div_scenario][norm] = dict()
            inf_times[i][div_scenario][norm] = dict()
            
            # Load regression model 
            model_path = res_path + div_scenario + '/' + i + "_regression_"
            if norm != 'no_norm':
                model_path += norm + '_'
            
            results[i][div_scenario][norm], ex_time = generate_reg_results(model_path, data[i]['X_test'],
                                                                           data[i]['y_reg_test'],
                                                                           data[i]['y_reg_norm_test'],
                                                                           data[i]['div_info_test'],
                                                                           data[i]['resc_factor_test'],
                                                                           div_scenario, label, norm)
            inf_times[i][div_scenario][norm] = ex_time

--- 674 tips ---

NameError: name 'generate_reg_results' is not defined

## Inference time

In [7]:
for i in inf_times:
    t = []
    for scenario in inf_times[i]:
        t.append(inf_times[i][scenario]['norm'])
   
    print(f"\nInference time statistics for {i}:")
    print(f"Mean: {np.mean(t):.4f}")
    print(f"Standard deviation: {np.std(t):.4f}")
    print(f"Minimum: {np.min(t):.4f}")
    print(f"Maximum: {np.max(t):.4f}")

Inference time statistics for 674:
Mean: 0.7927
Standard deviation: 1.1418
Minimum: 0.2216
Maximum: 3.3449

Inference time statistics for 489:
Mean: 0.2362
Standard deviation: 0.0300
Minimum: 0.1930
Maximum: 0.2676

Inference time statistics for 87:
Mean: 0.2382
Standard deviation: 0.0362
Minimum: 0.1889
Maximum: 0.2883

## Training time

In [8]:
for i in n_tips:
    train_times = []
    
    for label in np.unique(data[i]['div_info_test']):
        div_scenario = label.split('/')[1].split('_')[0]
        
        # Load regression model 
        model_path = res_path + div_scenario + '/' + i + "_regression_"

        with open(model_path + 'model_data.pkl', 'rb') as f:
            n_params, train_time = pickle.load(f)
                
        train_times.append(train_time)
    
    print('\nTraining times for', i, 'tips')
    print('-'*5)
    print('Mean:', np.mean(train_times))
    print('Std Dev:', np.std(train_times))
    print('Max:', np.max(train_times))
    print('Min:', np.min(train_times))

Training times for 674 tips
-----
Mean: 80.98654202620189
Std Dev: 23.909542822776093
Max: 121.00370073318481
Min: 53.84978413581848

Training times for 489 tips
-----
Mean: 146.08997031052908
Std Dev: 40.89618029143705
Max: 204.01095628738403
Min: 106.88540458679199

Training times for 87 tips
-----
Mean: 178.52716255187988
Std Dev: 47.54313057765572
Max: 278.6980650424957
Min: 133.32786893844604

# Regression metrics MAE vs MAE_norm

In [9]:
div_scenario = list(results[list(results.keys())[0]].keys())
get_regression_norm_results(results, '674', div_scenario, 'norm')

           norm no_norm
MAE      6.6471  0.9100
MAE_norm 4.8571  1.7434

In [10]:
div_scenario = list(results[list(results.keys())[0]].keys())
get_regression_norm_results(results, '489', div_scenario, 'norm')

           norm no_norm
MAE      6.3643  0.8653
MAE_norm 4.2064  1.6158

In [11]:
div_scenario = list(results[list(results.keys())[0]].keys())
get_regression_norm_results(results, '87', div_scenario, 'norm')

           norm no_norm
MAE      6.7094  0.9587
MAE_norm 5.3895  1.9278

## Comparison between diversification scenarios

In [12]:
get_regression_div_results(results, '674', 'BD', 'norm')

              r      a lambda     mu
MAE      1.1900 0.0940 1.2742 0.3312
MAE_norm 0.7580 0.0940 0.8178 0.0859

In [13]:
get_regression_div_results(results, '674', 'HE', 'norm')

              r      a lambda     mu
MAE      0.4450 0.1704 0.4974 0.0555
MAE_norm 0.2817 0.1704 0.3410 0.0615

In [14]:
get_regression_div_results(results, '674', 'ME', 'norm')

              r      a    time   frac lambda     mu
MAE      0.9504 0.0755 33.5415 0.0500 2.1865 1.2539
MAE_norm 0.6602 0.0755 26.0458 0.0500 1.3647 0.7227

In [15]:
get_regression_div_results(results, '674', 'SR', 'norm')

             r0     r1     a0     a1    time lambda0 lambda1    mu0    mu1
MAE      1.4599 0.1349 0.0912 0.0934 16.3070  2.0013  0.5425 0.5590 0.4102
MAE_norm 0.8802 0.0959 0.0912 0.0934 11.5338  1.2297  0.4772 0.3688 0.3842

In [16]:
get_regression_div_results(results, '674', 'SAT', 'norm')

         lambda 0
MAE        9.4073
MAE_norm   5.9115

In [17]:
get_regression_div_results(results, '674', 'WW', 'norm')

             r0      r1     a0     a1     time lambda0 lambda1    mu0    mu1
MAE      1.2006 10.0092 0.1474 0.0903 144.9705  1.9398 17.4393 3.1385 7.5262
MAE_norm 0.7143  7.0542 0.1474 0.0903 114.1477  1.1808 13.1925 1.8926 6.2520

In [12]:
from tensorflow.keras.models import load_model

In [14]:
n_trees_tested = 100
results = dict()
inf_times = dict()

for i in n_tips:
    print('---', i, 'tips ---')
    results[i] = dict()
    inf_times[i] = dict()
    
    for label in np.unique(data[i]['div_info_test']):
        div_scenario = label.split('/')[1].split('_')[0]
        results[i][div_scenario] = dict()
        inf_times[i][div_scenario] = dict()
        
        
        #Load the model
        model_path = res_path + div_scenario + '/' + i + "_regression_"
        nn_model = load_model(model_path + 'model.keras')
        
        #Predict
        start_time = time()
        pred = nn_model.predict(np.expand_dims(data[i]['X_test'][data[i]['div_info_test'] == label], axis=2))
        ex_time = time() - start_time
        print("--- Inference time: ", div_scenario, "scenario &", ex_time, "seconds ---")  
        
        #Load the real parameter values and the rescale factor for rescaling the predictions  
        y_reg_test = data[i]['y_reg_test'][data[i]['div_info_test'] == label]
        y_reg_test = [np.array(elem) for elem in y_reg_test]
        real = y_reg_test
        
        resc_factor_test = data[i]['resc_factor_test'][data[i]['div_info_test'] == label]
            
        #Rescale the corresponding parameter values     
        if div_scenario == "BD" or div_scenario == "HE" or div_scenario == "SAT":
            
            pred[:, 0] = pred[:, 0] / resc_factor_test
        elif div_scenario == "ME":
            
            pred[:, 0] = pred[:, 0] / resc_factor_test
            pred[:, 2] = pred[:, 2] / resc_factor_test
        else:

            pred[:, 0] = pred[:, 0] / resc_factor_test
            pred[:, 1] = pred[:, 1] / resc_factor_test
            pred[:, 4] = pred[:, 4] / resc_factor_test
            
        #Clip the values 
        
        if div_scenario == "BD":
            min_value = np.array([0.01, 0.01])            
            max_value = np.array([4, 0.5])                        
            
        elif div_scenario == "HE":
            min_value = np.array([0.01, 0.8])            
            max_value = np.array([4, 0.9])   
                        
        elif div_scenario == "SAT":
            min_value = np.array([0.01])            
            max_value = np.array([4])  
  
            
        elif div_scenario == "ME":
            min_value = np.array([0.01, 0.3, 3, 0.1])            
            max_value = np.array([1, 0.8, 20, 0.3]) 
        
        elif div_scenario == "SR":
            min_value = np.array([0.25, 0.01, 0.05, 0.55, 3])            
            max_value = np.array([1.99, 1, 0.5, 0.95, 20])         
        
        else: 
            min_value = np.array([-0.2, 0.5, 1.3, 0.25, 3])            
            max_value = np.array([-0.01, 1.5, 2, 0.6, 20])   
        
        clip_pred = np.clip(pred, min_value, max_value)

        clipped_perc = (np.sum(pred != clip_pred, axis=0)/pred.shape[0])*100
        clipped_below = (np.sum(pred < min_value, axis=0) / pred.shape[0]) * 100
        clipped_above = (np.sum(pred > max_value, axis=0) / pred.shape[0]) * 100
        
        results[i][div_scenario]["clipped_perc"] = clipped_perc
        results[i][div_scenario]["clipped_above"] = clipped_above
        results[i][div_scenario]["clipped_below"] = clipped_below
                   
        #Estimate the errors         
        abs_error = abs(clip_pred-real)
        raw_error = clip_pred-real
        r_error = abs((clip_pred - real)/ real)
        #Save the results
        results[i][div_scenario]['raw_error'] = raw_error
        results[i][div_scenario]['abs_error'] = abs_error
        results[i][div_scenario]['real_values'] = real
        
        results[i][div_scenario]['MAE'] = np.mean(abs_error, axis=0)
        results[i][div_scenario]['MRE'] = np.mean(r_error, axis=0)
        
        inf_times[i][div_scenario] = ex_time

--- 674 tips ---
--- Inference time:  BD scenario & 2.1193525791168213 seconds ---
--- Inference time:  HE scenario & 0.18628859519958496 seconds ---
--- Inference time:  ME scenario & 0.21035385131835938 seconds ---
--- Inference time:  SAT scenario & 0.18504571914672852 seconds ---
--- Inference time:  SR scenario & 0.24967694282531738 seconds ---
--- Inference time:  WW scenario & 0.24673080444335938 seconds ---
--- 489 tips ---
--- Inference time:  BD scenario & 0.2404942512512207 seconds ---
--- Inference time:  HE scenario & 0.16238188743591309 seconds ---
--- Inference time:  ME scenario & 0.19897818565368652 seconds ---
--- Inference time:  SAT scenario & 0.1536412239074707 seconds ---
--- Inference time:  SR scenario & 0.2007589340209961 seconds ---
--- Inference time:  WW scenario & 0.19742202758789062 seconds ---
--- 87 tips ---
--- Inference time:  BD scenario & 0.18311047554016113 seconds ---
--- Inference time:  HE scenario & 0.14847493171691895 seconds ---
--- Inference time:  ME scenario & 0.15793871879577637 seconds ---
--- Inference time:  SAT scenario & 0.12458395957946777 seconds ---
--- Inference time:  SR scenario & 0.17646050453186035 seconds ---
--- Inference time:  WW scenario & 0.18060517311096191 seconds ---

In [15]:
n_tips = ['674', '489', '87']
div_scenarios = ['BD', 'HE', 'ME', 'SAT', 'SR', 'WW']

In [24]:
for tip in n_tips: 
    print("\n---------" + str(tip) + "---------\n" )
    for scenario in div_scenarios: 
        print(scenario)
        data = get_regression_metrics(results, tip, scenario, 'MAE')
        print(data)

---------674---------

BD
         r      a
MAE 0.1014 0.0696
HE
         r      a
MAE 0.2117 0.0178
ME
         r      a   time   frac
MAE 0.0428 0.0716 5.0394 0.0491
SAT
     lambda 0
MAE    0.0701
SR
        r0     r1     a0     a1   time
MAE 0.0743 0.0219 0.1032 0.0949 3.5430
WW
        r0     r1     a0     a1   time
MAE 0.0338 0.0969 0.1521 0.0904 1.9678

---------489---------

BD
         r      a
MAE 0.1349 0.0743
HE
         r      a
MAE 0.1924 0.0198
ME
         r      a   time   frac
MAE 0.0350 0.0724 4.8132 0.0513
SAT
     lambda 0
MAE    0.0699
SR
        r0     r1     a0     a1   time
MAE 0.0509 0.0204 0.0976 0.0992 2.9160
WW
        r0     r1     a0     a1   time
MAE 0.0321 0.0910 0.1179 0.0816 2.2050

---------87---------

BD
         r      a
MAE 0.2593 0.1071
HE
         r      a
MAE 0.2723 0.0244
ME
         r      a   time   frac
MAE 0.0362 0.0862 5.2812 0.0444
SAT
     lambda 0
MAE    0.1823
SR
        r0     r1     a0     a1   time
MAE 0.0756 0.0199 0.1135 0.0894 2.9859
WW
        r0     r1     a0     a1   time
MAE 0.0294 0.1501 0.1345 0.0772 2.6504

In [22]:
for tip in n_tips: 
    print("\n---------" + str(tip) + "---------\n" )
    for scenario in div_scenarios: 
        print(scenario)
        data = get_regression_metrics(results, tip, scenario, 'MRE')
        print(data)

---------674---------

BD
         r      a
MRE 0.0558 0.5564
HE
         r      a
MRE 0.1036 0.0210
ME
         r      a   time   frac
MRE 0.1487 0.1565 0.6848 0.2912
SAT
     lambda 0
MRE    0.0352
SR
        r0     r1     a0     a1   time
MRE 0.1131 0.5298 0.5803 0.1306 0.6930
WW
        r0     r1     a0     a1   time
MRE 0.5894 0.0989 0.0936 0.2263 0.1856

---------489---------

BD
         r      a
MRE 0.0672 0.8992
HE
         r      a
MRE 0.1140 0.0233
ME
         r      a   time   frac
MRE 0.1246 0.1556 0.5980 0.2925
SAT
     lambda 0
MRE    0.0350
SR
        r0     r1     a0     a1   time
MRE 0.0830 0.4858 0.5986 0.1387 0.4975
WW
        r0     r1     a0     a1   time
MRE 0.4096 0.1049 0.0746 0.2167 0.2098

---------87---------

BD
         r      a
MRE 0.1216 0.8995
HE
         r      a
MRE 0.1387 0.0291
ME
         r      a   time   frac
MRE 0.1736 0.1705 0.6884 0.2345
SAT
     lambda 0
MRE    0.0881
SR
        r0     r1     a0     a1   time
MRE 0.1476 0.4796 0.6985 0.1272 0.5985
WW
        r0     r1     a0     a1   time
MRE 0.4289 0.1839 0.0852 0.2038 0.2217

In [23]:
for tip in n_tips:
    print("\n---------" + str(tip) + "---------\n" )
    for scenario in div_scenarios:
        print(scenario)
        df_tot, df_below, df_above = get_clipping_results(results, tip, scenario)
        print(df_tot)
        print(df_below)
        print(df_above, "\n")

---------674---------

BD
               r      a
Clipped % 1.0000 2.0000
             r      a
Below % 0.0000 1.0000
             r      a
Above % 1.0000 1.0000

HE
               r      a
Clipped % 8.0000 2.0000
             r      a
Below % 0.0000 0.0000
             r      a
Above % 8.0000 2.0000

ME
               r      a    time   frac
Clipped % 0.0000 0.0000 10.0000 0.0000
             r      a   time   frac
Below % 0.0000 0.0000 7.0000 0.0000
             r      a   time   frac
Above % 0.0000 0.0000 3.0000 0.0000

SAT
           lambda 0
Clipped %    1.0000
         lambda 0
Below %    0.0000
         lambda 0
Above %    1.0000

SR
              r0     r1     a0     a1   time
Clipped % 0.0000 0.0000 0.0000 0.0000 6.0000
            r0     r1     a0     a1   time
Below % 0.0000 0.0000 0.0000 0.0000 6.0000
            r0     r1     a0     a1   time
Above % 0.0000 0.0000 0.0000 0.0000 0.0000

WW
              r0     r1     a0     a1   time
Clipped % 1.0000 0.0000 0.0000 0.0000 2.0000
            r0     r1     a0     a1   time
Below % 1.0000 0.0000 0.0000 0.0000 0.0000
            r0     r1     a0     a1   time
Above % 0.0000 0.0000 0.0000 0.0000 2.0000


---------489---------

BD
               r      a
Clipped % 1.0000 0.0000
             r      a
Below % 0.0000 0.0000
             r      a
Above % 1.0000 0.0000

HE
               r      a
Clipped % 5.0000 0.0000
             r      a
Below % 0.0000 0.0000
             r      a
Above % 5.0000 0.0000

ME
               r      a   time   frac
Clipped % 0.0000 0.0000 8.0000 0.0000
             r      a   time   frac
Below % 0.0000 0.0000 4.0000 0.0000
             r      a   time   frac
Above % 0.0000 0.0000 4.0000 0.0000

SAT
           lambda 0
Clipped %    2.0000
         lambda 0
Below %    0.0000
         lambda 0
Above %    2.0000

SR
              r0     r1     a0     a1   time
Clipped % 4.0000 0.0000 0.0000 0.0000 4.0000
            r0     r1     a0     a1   time
Below % 4.0000 0.0000 0.0000 0.0000 4.0000
            r0     r1     a0     a1   time
Above % 0.0000 0.0000 0.0000 0.0000 0.0000

WW
              r0     r1     a0     a1   time
Clipped % 2.0000 0.0000 0.0000 0.0000 3.0000
            r0     r1     a0     a1   time
Below % 2.0000 0.0000 0.0000 0.0000 0.0000
            r0     r1     a0     a1   time
Above % 0.0000 0.0000 0.0000 0.0000 3.0000


---------87---------

BD
               r      a
Clipped % 6.0000 0.0000
             r      a
Below % 0.0000 0.0000
             r      a
Above % 6.0000 0.0000

HE
               r      a
Clipped % 4.0000 0.0000
             r      a
Below % 0.0000 0.0000
             r      a
Above % 4.0000 0.0000

ME
               r      a   time   frac
Clipped % 0.0000 0.0000 7.0000 0.0000
             r      a   time   frac
Below % 0.0000 0.0000 5.0000 0.0000
             r      a   time   frac
Above % 0.0000 0.0000 2.0000 0.0000

SAT
           lambda 0
Clipped %    3.0000
         lambda 0
Below %    0.0000
         lambda 0
Above %    3.0000

SR
              r0     r1     a0     a1   time
Clipped % 3.0000 0.0000 0.0000 0.0000 9.0000
            r0     r1     a0     a1   time
Below % 3.0000 0.0000 0.0000 0.0000 8.0000
            r0     r1     a0     a1   time
Above % 0.0000 0.0000 0.0000 0.0000 1.0000

WW
              r0     r1     a0     a1   time
Clipped % 0.0000 3.0000 0.0000 0.0000 2.0000
            r0     r1     a0     a1   time
Below % 0.0000 3.0000 0.0000 0.0000 0.0000
            r0     r1     a0     a1   time
Above % 0.0000 0.0000 0.0000 0.0000 2.0000